### PR TITLE
add LIKE and ILIKE functionality

### PR DESCRIPTION
**Pull request by Liamraystanley**
I think that until there is a possible overhaul to the `find()` api (abstracted to feel like the actual SQLAlchemy api, as some have discussed), I would like to add a few additional column operators to `find()`.

This format may also suit issue #128 where we could bootstrap `__ge__`, `__gt__`, `__le__`, and `__lt__` from the [SQLAlchemy Column Operator](http://docs.sqlalchemy.org/en/rel_0_9/core/sqlelement.html#sqlalchemy.sql.operators.ColumnOperators.match) list as a way of implementing these features until a more elegant method is developed.

An example of these operators (`LIKE` and `ILIKE`), could be something like:

```python
# Attempt to get "John Doe"
john = table.find_one(name='John %', _like=['name'])
```

I know that the goal of dataset is to abstract the actual ORM from the end user, and that more complex queries should be handled manually, or by something like SQLAlchemy itself.. Though if we can simplify things enough to where it both does not interfere with the basic concept of the ORM, while allowing more advanced users to not have to jump the bridge and take on a much more complex ORM-based wrapped, I think I could dig dataset quite a bit more :+1:

Let me know your thoughts on this, as I am very interested to see these features added.

### CODE REVIEW

**Comment by stefanw** [comment]
Reimplementing SQLAlchemy operators seems to me like reinventing an ORM – which is not the goal of dataset. I would rather see an API that allows to use proper SQLAlchemy query constructs within dataset as a fallback to missing query functionality. But I'm unsure how this would look like.

**Comment by pudo** [comment]
I also feel some reluctance to accept this: it feels like a solution to a very specific need, while not really extensible towards other problems (how would this approach allow for AND and OR queries?). Perhaps we could instead have a few classes like this: 

```python
import dataset
eng = dataset.connect()
table = eng['table']
cond = dataset.filter.like('%foo%')
table.find(column_x=cond)
```

What do you think, @Liamraystanley ?

**Comment by Liamraystanley** [comment]
For filtering, and adding support for additional [column operators](http://docs.sqlalchemy.org/en/rel_0_9/core/sqlelement.html#sqlalchemy.sql.operators.ColumnOperators.match), that approach does feel much more natural, and that should be something that can be implemented pretty easily.

Though, as for **AND**/**OR** queries, I am not sure how this would allow support for those operators. Do you have any thoughts on how one of those operators may be implemented?

**Comment by pudo** [comment]
Hm, good question -- you'd need to bind the column filters before putting them in the ``AND``/``OR``.
Maybe this?
```python
q = dataset.query(column_x='foo').or(column_y='bar')
table.find(q)
```
This starts to look a lot like SQLAlchemy syntax :) Any way we can just expose that properly?

**Comment by stefanw** [comment]
How about having a `where` method on `Table` that calls [`Select.where`](http://docs.sqlalchemy.org/en/latest/core/selectable.html#sqlalchemy.sql.expression.Select.where) and gives the same thing back as `.find`?

Example:

```python
results = table.where(table.table.c.name.like('John %'))

results = table.where(table.table.c.count > 5)
```

The `table.table.c.name` thing is slightly ugly, but that's currently how you would access the underlying sqlalchemy table. Also this would not allow for ordering or limiting the result set. Possibly some kind of proxy needs to be returned. Maybe like this:

```python
proxy_obj = table.where(table.table.c.name.like('John %'))
proxy_obj = proxy_obj.order_by(table.table.c.email_address)
dataset_iterator = proxy_obj.execute()
```

**Comment by pudo** [comment]
This can now be accomplished via https://github.com/pudo/dataset/pull/161 -- closing in favor of that simpler solution.

**Pull request closed without merging**
