### PR TITLE
Reflect views.

### PR DESCRIPTION
**Pull request by saimn**
Currently views does not appear in the list of tables, this allows to add views.
Maybe you prefer to have an argument in `connect` for this ?

### CODE REVIEW

**Comment by pudo** [comment]
Oh, neat simple pull! I would say that an argument might be nice, but it should be set to ``True`` by default. Would you update?

**Comment by saimn** [comment]
@pudo : done :)
I have also modified the import in `dataset/__init__.py` to make Travis happy.

**Comment by pudo** [comment]
Looks great, thank you sir!

**Comment by pudo** [comment]
@saimn - damn! Looks like there is some driver-specific stuff going wrong. Can you have a quick look? 

https://travis-ci.org/pudo/dataset/builds/51255901

**Comment by stefanw** [comment]
It looks like PyPI reset connection during install, restarted jobs, fingers crossed.

**Comment by saimn** [comment]
Hmm strange, the build before the merge went fine (https://travis-ci.org/pudo/dataset/builds/51245385).
It seems Travis has some connectivity issues these days when installing dependencies, I have seen this on another project.

**Comment by stefanw** [comment]
Went through fine now, thanks!

**Pull request merged**
