### PR TITLE
Added insert_ignore and changed upsert.

### PR DESCRIPTION
**Pull request by saun4app**
The different between insert_ignore and upsert is that when the row exists, insert_ignore does change the existing row.  It is useful when we don't want to change existing row, and should be updating every time.

### CODE REVIEW

**Comment by pudo** [comment]
Sorry, just to check: ``insert_ignore`` **doesn't** change the existing row, right? That looks useful.

**Comment by saun4app** [comment]
You are correct.  insert_ignore share the same check with upset, except it does nothing when a row exists.

**Comment by saun4app** [comment]
@pudo, what is your current thinking about this pull request?

**Comment by pudo** [comment]
Sorry for the delay! I'll push out a new version early next week!

**Pull request merged**
