### PR TITLE
Use fetchmany to prevent huge tables loaded at once

### PR DESCRIPTION
**Pull request by twds**
I found that `dataset.Table.find` will break the query into chunks of small queries which maybe unsafe in multi-connection cases.

Instead of split the query into small queries and call `fetchall()`, I think just run one query and iteratively call `fetchmany(step)` maybe better.

How about your idea?

### CODE REVIEW

**Comment by pudo** [comment]
Thanks, @twds - I'd been starting to wonder about ``ResultIter`` myself. Your implementation is much more in line with what it says on the tin. My only question is about database support - I vaguely recall SQLite not supporting incremental cursors. Do you know what the verdict is on this?

**Comment by twds** [comment]
@pudo I'm not quite sure what you mean by `SQLite not supporting incremental cursors`.
I make some experiments with SQLAlchemy and sqlite3, `cursor.fetchmany()` both works fine on SQLite db.

https://docs.python.org/2/library/sqlite3.html

**Comment by pudo** [comment]
Thanks very much for the PR, @twds !

**Comment by stefanw** [comment]
I did some `flake8` clean up, but it looks like this broke the build. Specifically it looks like infinite recursion is going on in the new iterator. @twds care to check?

https://travis-ci.org/pudo/dataset/builds/97883940

**Comment by twds** [comment]
@stefanw 
Update the code
https://github.com/pudo/dataset/pull/145

Now the test cases passed
https://travis-ci.org/pudo/dataset/builds/97926163

**Pull request merged**
