### PR TITLE
Guess LargeBinary as column type when sample is BytesIO instance

### PR DESCRIPTION
**Pull request by extempore**

### CODE REVIEW

**Comment by pudo** [comment]
Interesting PR! I don't have enough experience in database blobbiness to really figure out the implications. What do you think, @stefanw? If there's no protest, we should try it ;)

**Comment by stefanw** [comment]
Seems to make sense. A test for this would be awesome!

**Comment by pudo** [comment]
Fancy, fancy. @extempore would you mind?

**Comment by extempore** [comment]
I'm about to give this a try now. I don't have much experience with sqlalchemy, so I wonder how the BytesIO objects will be handled.

I glanced at current tests and it seems if I add another column in sample_data, it will break other tests. Any suggestions?

**Comment by extempore** [comment]
BytesIO didn't do the trick but I discovered that SQLite TEXT columns can happily contain both unicode and blobs. 

When you do `tbl.insert({'databin': buffer(my_str)})` in a TEXT column, it works, and you also get a buffer when you read the row back. If you try to insert my_str without the buffer you get a unicode error.

When you use the types option on insert  `tbl.insert({'databin': buffer(my_str)}, types={'databin':LargeBinary})`, it returns an str object when you read it back. If you try to insert my_str without the buffer, it works and  you don't get any errors.

So the sqlite driver will return `buffer` when you read a blob from a TEXT column and `str` when you read from a BLOB column. That's... intuitive. I wonder what the other drivers do.

On Python3 we could guess LargeBinary when we see a bytestring, but on Python2 I don't want LargeBinary when I insert `str`, which is why I went for `BytesIO` initially.

So I will update the pull request and test for `buffer` instead of `BytesIO`.

```
import dataset
from binascii import unhexlify

if __name__ == '__main__':
    blob = '0100000000000000000000000000000000000000000000000000000000000000000000003ba3edfd7a7b12b27ac72c3e67768f617fc81bc3888a51323a9fb8aa4b1e5e4a29ab5f49ffff001d1dac2b7c0101000000010000000000000000000000000000000000000000000000000000000000000000ffffffff4d04ffff001d0104455468652054696d65732030332f4a616e2f32303039204368616e63656c6c6f72206f6e206272696e6b206f66207365636f6e64206261696c6f757420666f722062616e6b73ffffffff0100f2052a01000000434104678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef38c4f35504e51ec112de5c384df7ba0b8d578a4c702b6bf11d5fac00000000'
    b = unhexlify(blob)
    db = dataset.connect('sqlite:///blobs.sqlite')
    tbl = db['test_blobs']
    tbl.insert({'databin': buffer(b), 'dat': 'abcd'})
    tbl.insert({'dat': buffer(b), 'databin': 'abcd'})
    row = tbl.find_one(id=1)
    bb = row['databin']
    print type(bb)
    print type(row['dat'])
    l = len(str(bb))
    assert l == len(b)
    assert b == str(bb)
```

**Comment by extempore** [comment]
Turns out `buffer` doesn't exist in Python3. I don't really use 3 but this seems messy now. Any ideas?

For my current project, I think I'm gonna use `tbl.create_column('databin', LargeBinary)` to setup BLOB columns in advance, then I don't need to wrap strings in a `buffer` to insert.

**Comment by pudo** [comment]
@extempore maybe six could be useful in wrapping the version discrepancies? https://pythonhosted.org/six/#binary-and-text-data

**Pull request closed without merging**
