### PR TITLE
fix infinite recursion

### PR DESCRIPTION
**Pull request by twds**
fix the build failure
https://travis-ci.org/pudo/dataset/builds/97883940

### CODE REVIEW

**Comment by stefanw** [comment]
Thanks @twds! I had problems running tests locally and added the change in d16f1df8cd9c1ae2635979e158340b2bd19fb178 to check for a closed result proxy.

**Comment by twds** [comment]
@stefanw 
Got confused why the previous build failed at infinite recursion? (https://travis-ci.org/pudo/dataset/jobs/96836370)

It looks like whether auto close result proxy depends on the dev environment or lib versions? I have the problems with you today but I remembered that when I send this PR yesterday in another laptop, `fetchmany()` will always return empty list (instead of crash) even when all the data has been read. (I remember I had executed much more than one times when all data loaded)

I'll check it after back home, but I cannot find the code of test cases on https://travis-ci.org/pudo/dataset/jobs/96836370.

Could you please show me the link about the test cases?

Thanks

**Comment by stefanw** [comment]
I also couldn't figure out why tests passed on travis and not locally (haven't put too much time into it though). The closed result proxy failure does not appear on travis, only infinite recursion made it fail (obviously).

The commit for the travis job you mentioned ([pudo/dataset/jobs/96836370](https://travis-ci.org/pudo/dataset/jobs/96836370)) was done on commit 00b4efd02436f6d0205b491d4065f272354198c8 and failed on the [`test_distinct` test case](https://travis-ci.org/pudo/dataset/jobs/96836370#L530) ([code is here](https://github.com/pudo/dataset/blob/master/test/test_persistence.py#L391)) with infinite recursion which then breaks the whole test run with a a `maximum recursion depth exceeded`.

**Comment by twds** [comment]
@stefanw 
http://docs.sqlalchemy.org/en/latest/changelog/migration_10.html#resultproxy-auto-close-is-now-a-soft-close

The sqlalchemy version in my laptops are 0.9.9 and 1.0.10, so the first will crash while the second will pass the tests.

**Comment by stefanw** [comment]
Good find, that solves the mystery. With d16f1df8cd9c1ae2635979e158340b2bd19fb178 in place it will now work on either version.

**Pull request merged**
